In [25]:
import pandas as pd
import os

# Загрузка и пример данных

In [24]:
data = pd.read_csv('data/data_2025-03-11_13-10-57.csv')
len(data)

1693

In [22]:
data.head(10)

,data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],...,data[2044],data[2045],data[2046],data[2047],Num Pack,Antenna,Window,Diag,System_type,Drone_type
0,-47.015938,-73.762985,-52.380436,-6.043974,-0.747477,-99.382260,-2.493612,-32.996174,-90.407326,-29.517735,...,-96.402090,-77.552390,-55.197815,-1.167421,[1],[1],[1],[1],Type 1,DJI
1,-95.541490,-42.011105,-61.169205,-73.411110,-59.098923,-71.584350,-2.937642,-94.660960,-33.643314,-27.411760,...,-70.594110,-15.404800,-83.549980,-63.810223,[2],[1],[1],[1],Type 1,DJI
2,-69.125570,-92.523330,-79.021380,-21.387213,-81.428560,-81.962265,-15.713350,-15.500656,-89.547430,-46.631870,...,-94.545910,-65.130810,-20.779472,-60.196690,[3],[1],[1],[1],Type 1,DJI
3,-45.878350,-5.602477,-94.128080,-0.121163,-68.128006,-81.369090,-18.733950,-63.426403,-67.339750,-25.943070,...,-64.212840,-29.891123,-4.528070,-43.362470,[4],[1],[1],[1],Type 1,DJI
4,-61.971830,-18.126886,-84.561430,-94.667960,-38.107853,-76.621170,-95.773620,-21.360315,-86.296210,-59.784286,...,-64.292015,-45.352062,-28.654871,-0.606470,[5],[1],[1],[1],Type 1,DJI
5,-52.115486,-57.333897,-65.067800,-35.568165,-55.910820,-23.079980,-41.669292,-88.914770,-94.240110,-35.026276,...,-22.070463,-34.871030,-45.062904,-31.431581,[6],[1],[1],[1],Type 1,DJI
6,-23.511372,-27.099980,-17.545242,-35.102280,-42.007782,-98.304790,-81.823110,-22.104784,-93.181040,-33.093307,...,-91.890260,-9.952101,-79.926140,-27.967924,[7],[1],[1],[1],Type 1,DJI
7,-44.549740,-86.026500,-10.586591,-8.671704,-52.579346,-68.681175,-13.392987,-41.108288,-17.485113,-77.879960,...,-46.075370,-91.787540,-31.059578,-97.354590,[8],[1],[1],[1],Type 1,DJI
8,-19.083382,-3.409722,-29.789871,-76.982120,-48.246113,-58.851852,-21.602766,-25.976898,-51.339890,-95.744030,...,-59.505962,-91.974460,-15.168640,-41.337982,[9],[1],[1],[1],Type 1,DJI
9,-74.432130,-99.444275,-61.801100,-3.210750,-50.972240,-83.170840,-66.561220,-2.345487,-48.669800,-66.016390,...,-90.872856,-91.323500,-80.208820,-67.641716,[10],[1],[1],[1],Type 1,DJI

# Берем только отсчеты

In [4]:
values_data = data.drop(columns=['Num Pack', 'Antenna', 'Window', 'Diag', 'System_type', 'Drone_type'])
values_data.head(5)

,data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7],data[8],data[9],...,data[2038],data[2039],data[2040],data[2041],data[2042],data[2043],data[2044],data[2045],data[2046],data[2047]
0,-24.638887,-34.694380,-62.711327,-85.346470,-2.325876,-63.860844,-71.853570,-51.651120,-79.047430,-15.268421,...,-51.482395,-10.479684,-72.665050,-30.725937,-25.978498,-89.214640,-38.790250,-40.354473,-55.170640,-59.429150
1,-51.570360,-38.005943,-94.958534,-29.464550,-58.792526,-25.212315,-77.415930,-57.092777,-21.809183,-27.032219,...,-5.905282,-30.287598,-96.223816,-59.939323,-98.705605,-95.518020,-81.342186,-3.440104,-51.567210,-27.897266
2,-71.166960,-11.873010,-17.895866,-19.648565,-67.958310,-87.125830,-34.747547,-43.275837,-19.829779,-73.918590,...,-18.988920,-88.974720,-40.680760,-9.642829,-64.536530,-84.643390,-94.646480,-97.998490,-21.993816,-7.745629
3,-93.769500,-54.500645,-8.928077,-29.886738,-6.417540,-63.967980,-31.745491,-71.462640,-45.055946,-78.488780,...,-64.562430,-2.495928,-85.702380,-31.259325,-86.379280,-8.305665,-76.477390,-67.465430,-61.185787,-84.852960
4,-99.350810,-83.995650,-53.198055,-73.645195,-37.522617,-89.576740,-83.469536,-9.407357,-75.520150,-72.565216,...,-65.410960,-6.337542,-2.372674,-34.885410,-42.890700,-99.462050,-16.964010,-58.574720,-23.917978,-73.824150

# Отсчеты первого наблюдения

In [6]:
values_data.iloc[0]

data[0]      -24.638887
data[1]      -34.694380
data[2]      -62.711327
data[3]      -85.346470
data[4]       -2.325876
                ...
data[2043]   -89.214640
data[2044]   -38.790250
data[2045]   -40.354473
data[2046]   -55.170640
data[2047]   -59.429150
Name: 0, Length: 2048, dtype: float64